/* GENERATED by scripts/build-ai-work.mjs - do not edit by hand.
   Re-run it after anything lands in or leaves
   public/assets/SC Website Revamp/05. AI work.

   89 assets, from 100 files on disk - the rest were
   byte-identical duplicates of something already here. Stills are
   re-encoded webp in /assets/ai; films are referenced where they were
   delivered. See lib/ai-content.ts for the shape and what the grid does
   with the tags. */
import type { AiAsset } from "./ai-content";

export const AI_WORK: AiAsset[] = [
  {
    "id": "halloween",
    "kind": "static",
    "title": "Halloween",
    "brand": "",
    "src": "/assets/ai/halloween.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "1",
    "kind": "video",
    "title": "Untitled film",
    "brand": "",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/Mixed%20Videos/Copy%20of%201_1.mp4",
    "w": 1080,
    "h": 1920,
    "tags": [
      "video"
    ]
  },
  {
    "id": "ai",
    "kind": "cgi",
    "title": "Untitled film",
    "brand": "",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/CGI%20videos/Copy%20of%20AI%20.mp4",
    "w": 1080,
    "h": 1920,
    "tags": [
      "cgi"
    ]
  },
  {
    "id": "skiing",
    "kind": "static",
    "title": "Skiing",
    "brand": "",
    "src": "/assets/ai/skiing.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "352stone-3d-kv",
    "kind": "video",
    "title": "352stone 3D KV",
    "brand": "352 Stone",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/Mixed%20Videos/Copy%20of%20352Stone_3D_KV_noPrice16x9(1).mp4",
    "w": 1920,
    "h": 1080,
    "tags": [
      "video"
    ]
  },
  {
    "id": "ai-waffle-video-01",
    "kind": "cgi",
    "title": "AI Waffle Video 01",
    "brand": "",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/CGI%20videos/Copy%20of%20AI_Waffle_Video_Packaged_Revised_FINAL_01.mp4",
    "w": 1080,
    "h": 1920,
    "tags": [
      "cgi"
    ]
  },
  {
    "id": "ai-grid-01",
    "kind": "static",
    "title": "AI Grid 01",
    "brand": "",
    "src": "/assets/ai/ai-grid-01.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "adding-comforting-scenes-in-your-life",
    "kind": "video",
    "title": "Adding Comforting Scenes In Your Life",
    "brand": "",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/Mixed%20Videos/Copy%20of%20Adding%20comforting%20scenes%20in%20your%20life.mp4",
    "w": 1080,
    "h": 1920,
    "tags": [
      "video"
    ]
  },
  {
    "id": "bajaj-cgi",
    "kind": "cgi",
    "title": "Bajaj CGI",
    "brand": "Bajaj",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/CGI%20videos/Copy%20of%20Bajaj_CGI.mp4",
    "w": 2160,
    "h": 3840,
    "tags": [
      "cgi"
    ]
  },
  {
    "id": "ai-grid-02",
    "kind": "static",
    "title": "AI Grid 02",
    "brand": "",
    "src": "/assets/ai/ai-grid-02.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "admired",
    "kind": "video",
    "title": "Admired",
    "brand": "",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/Mixed%20Videos/Copy%20of%20Admired_V4(1).mp4",
    "w": 1920,
    "h": 1080,
    "tags": [
      "video"
    ]
  },
  {
    "id": "coconut-water-gif2",
    "kind": "cgi",
    "title": "Coconut Water GIF2",
    "brand": "",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/CGI%20videos/Copy%20of%20Coconut_Water_GIF2_V4.mp4",
    "w": 1080,
    "h": 1920,
    "tags": [
      "cgi"
    ]
  },
  {
    "id": "ai-grid-03",
    "kind": "static",
    "title": "AI Grid 03",
    "brand": "",
    "src": "/assets/ai/ai-grid-03.webp",
    "w": 1079,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "announcement-video-back-sticker",
    "kind": "video",
    "title": "Announcement Video Back Sticker",
    "brand": "",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/Mixed%20Videos/Copy%20of%20Announcement%20Video%20back%20sticker.mp4",
    "w": 1080,
    "h": 1920,
    "tags": [
      "video"
    ]
  },
  {
    "id": "aghori-title-animation",
    "kind": "cgi",
    "title": "Aghori Title Animation",
    "brand": "Aghori",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/CGI%20videos/Copy%20of%20Copy%20of%20Aghori%20Title%20Animation.mp4",
    "w": 1920,
    "h": 1080,
    "tags": [
      "cgi"
    ]
  },
  {
    "id": "moon",
    "kind": "static",
    "title": "Moon",
    "brand": "",
    "src": "/assets/ai/moon.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "ashutosh-character-promo-yt-03",
    "kind": "video",
    "title": "Ashutosh Character Promo YT 03",
    "brand": "",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/Mixed%20Videos/Copy%20of%20Ashutosh%20Character%20promo_YT_03%20With%20endslate.mp4",
    "w": 1080,
    "h": 1920,
    "tags": [
      "video"
    ]
  },
  {
    "id": "em5-aghori",
    "kind": "cgi",
    "title": "EM5 Aghori",
    "brand": "Aghori",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/CGI%20videos/Copy%20of%20Copy%20of%20EM5_Aghori.mp4",
    "w": 1080,
    "h": 1920,
    "tags": [
      "cgi"
    ]
  },
  {
    "id": "5",
    "kind": "static",
    "title": "Welcome the Royal",
    "brand": "Monarch",
    "src": "/assets/ai/5.webp",
    "w": 1350,
    "h": 2400,
    "tags": [
      "static"
    ]
  },
  {
    "id": "jhs-akotsk-ep-3-egg-cut",
    "kind": "video",
    "title": "JHS AKOTSK EP 3 Egg Cut",
    "brand": "JHS",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/Mixed%20Videos/Copy%20of%20JHS%20-%20AKOTSK%20EP%203%20Egg%20Cut%20V1.mp4",
    "w": 1080,
    "h": 1920,
    "tags": [
      "video"
    ]
  },
  {
    "id": "samurai-attack-reel-6",
    "kind": "cgi",
    "title": "SAMURAI ATTACK REEL 06",
    "brand": "Samurai",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/CGI%20videos/Copy%20of%20Copy%20of%20SAMURAI%20ATTACK%20REEL%20MAIN_6.mp4",
    "w": 1920,
    "h": 1080,
    "tags": [
      "cgi"
    ]
  },
  {
    "id": "ai-gaming",
    "kind": "static",
    "title": "AI Gaming",
    "brand": "",
    "src": "/assets/ai/ai-gaming.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "kiss-the-waffle",
    "kind": "video",
    "title": "Kiss The Waffle",
    "brand": "",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/Mixed%20Videos/Copy%20of%20Kiss%20the%20waffle.mp4",
    "w": 1080,
    "h": 1920,
    "tags": [
      "video"
    ]
  },
  {
    "id": "spiderpunk-coming-soon",
    "kind": "cgi",
    "title": "Spider-Punk Coming Soon",
    "brand": "Spider-Punk",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/CGI%20videos/Copy%20of%20Copy%20of%20SpiderPunk%20Coming%20Soon_V5.mp4",
    "w": 1080,
    "h": 1920,
    "tags": [
      "cgi"
    ]
  },
  {
    "id": "independence-day",
    "kind": "static",
    "title": "Independence Day",
    "brand": "",
    "src": "/assets/ai/independence-day.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "london-dry-bts-complex",
    "kind": "video",
    "title": "London Dry BTS Complex",
    "brand": "London Dry",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/Mixed%20Videos/Copy%20of%20London%20Dry%20BTS_complex.mp4",
    "w": 1080,
    "h": 1920,
    "tags": [
      "video"
    ]
  },
  {
    "id": "yippee-bau-halloween",
    "kind": "cgi",
    "title": "YIPPEE BAU Halloween",
    "brand": "Yippee",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/CGI%20videos/Copy%20of%20Copy%20of%20YIPPEE_BAU_Halloween_9x16_V2.mp4",
    "w": 1080,
    "h": 1920,
    "tags": [
      "cgi"
    ]
  },
  {
    "id": "ai-frisbee",
    "kind": "static",
    "title": "AI Frisbee",
    "brand": "",
    "src": "/assets/ai/ai-frisbee.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "reelvideo-57616",
    "kind": "video",
    "title": "Reel",
    "brand": "",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/Mixed%20Videos/Copy%20of%20Reelvideo-57616.mp4",
    "w": 720,
    "h": 1280,
    "tags": [
      "video"
    ]
  },
  {
    "id": "yippee-bau-navratri",
    "kind": "cgi",
    "title": "YIPPEE BAU Navratri",
    "brand": "Yippee",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/CGI%20videos/Copy%20of%20Copy%20of%20YIPPEE_BAU_Navratri_9x16_V1.mp4",
    "w": 1080,
    "h": 1920,
    "tags": [
      "cgi"
    ]
  },
  {
    "id": "nacho-ship",
    "kind": "static",
    "title": "Nacho Ship",
    "brand": "",
    "src": "/assets/ai/nacho-ship.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "meet-your-product-02",
    "kind": "video",
    "title": "Meet Your Product 02",
    "brand": "",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/Mixed%20Videos/Copy%20of%20meet%20your%20product%20%2002.mp4",
    "w": 1080,
    "h": 1350,
    "tags": [
      "video"
    ]
  },
  {
    "id": "havmor-heartbeat-reel",
    "kind": "cgi",
    "title": "Havmor Heartbeat Reel",
    "brand": "Havmor",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/CGI%20videos/Copy%20of%20Havmor_Heartbeat_reel.mp4",
    "w": 1080,
    "h": 1920,
    "tags": [
      "cgi"
    ]
  },
  {
    "id": "a-to-z-linkedin-post-5",
    "kind": "static",
    "title": "A To Z LinkedIn 05",
    "brand": "",
    "src": "/assets/ai/a-to-z-linkedin-post-5.webp",
    "w": 2000,
    "h": 2500,
    "tags": [
      "static"
    ]
  },
  {
    "id": "ai-waffle-video-02",
    "kind": "video",
    "title": "AI Waffle Video 02",
    "brand": "",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/STATICS/Copy%20of%20AI_Waffle_Video_Packaged_Revised_FINAL_02.mp4",
    "w": 1080,
    "h": 1920,
    "tags": [
      "video"
    ]
  },
  {
    "id": "havmor-kj-reel",
    "kind": "cgi",
    "title": "Havmor KJ Reel",
    "brand": "Havmor",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/CGI%20videos/Copy%20of%20Havmor_KJ_reel.mp4",
    "w": 1080,
    "h": 1920,
    "tags": [
      "cgi"
    ]
  },
  {
    "id": "ai-2",
    "kind": "static",
    "title": "Waffle on the Moon",
    "brand": "The Belgian Waffle Co.",
    "src": "/assets/ai/ai-2.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "ai-backgrounds",
    "kind": "video",
    "title": "AI Backgrounds",
    "brand": "",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/STATICS/Copy%20of%20Ai%20backgrounds_Revised.mp4",
    "w": 1080,
    "h": 1920,
    "tags": [
      "video"
    ]
  },
  {
    "id": "ai-reel",
    "kind": "cgi",
    "title": "AI Reel",
    "brand": "",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/CGI%20videos/Copy%20of%20ai%20reel.mp4",
    "w": 1080,
    "h": 1920,
    "tags": [
      "cgi"
    ]
  },
  {
    "id": "ai-carousel-6",
    "kind": "static",
    "title": "AI Carousel 06",
    "brand": "",
    "src": "/assets/ai/ai-carousel-6.webp",
    "w": 2000,
    "h": 2500,
    "tags": [
      "static"
    ]
  },
  {
    "id": "angry-sun",
    "kind": "video",
    "title": "Angry Sun",
    "brand": "",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/STATICS/Copy%20of%20Angry%20sun_V5.mp4",
    "w": 1080,
    "h": 1350,
    "tags": [
      "video"
    ]
  },
  {
    "id": "galentine-reel-f",
    "kind": "cgi",
    "title": "Galentine Reel F",
    "brand": "",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/CGI%20videos/Copy%20of%20galentine%20reel%20F.mp4",
    "w": 1080,
    "h": 1920,
    "tags": [
      "cgi"
    ]
  },
  {
    "id": "ai-jpg2",
    "kind": "static",
    "title": "Moonrise Waffle",
    "brand": "The Belgian Waffle Co.",
    "src": "/assets/ai/ai-jpg2.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "battery-low",
    "kind": "video",
    "title": "Battery Low",
    "brand": "",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/STATICS/Copy%20of%20Battery%20low_V5.mp4",
    "w": 1080,
    "h": 1920,
    "tags": [
      "video"
    ]
  },
  {
    "id": "ai-1",
    "kind": "static",
    "title": "Noodles in the Wild",
    "brand": "Yippee",
    "src": "/assets/ai/ai-1.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "bingo-x-swiggy-mad-angles",
    "kind": "video",
    "title": "Bingo X Swiggy Mad Angles",
    "brand": "Swiggy",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/STATICS/Copy%20of%20Bingo%20x%20Swiggy%20-%20Mad%20Angles%201x1.mp4",
    "w": 1080,
    "h": 1080,
    "tags": [
      "video"
    ]
  },
  {
    "id": "ai-2-2",
    "kind": "static",
    "title": "Noodle Valley",
    "brand": "Yippee",
    "src": "/assets/ai/ai-2-2.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "got-1",
    "kind": "video",
    "title": "GOT 01",
    "brand": "",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/STATICS/Copy%20of%20GOT_1.mp4",
    "w": 1080,
    "h": 1920,
    "tags": [
      "video"
    ]
  },
  {
    "id": "arcade",
    "kind": "static",
    "title": "Arcade",
    "brand": "",
    "src": "/assets/ai/arcade.webp",
    "w": 2048,
    "h": 2048,
    "tags": [
      "static"
    ]
  },
  {
    "id": "history-video-bsa",
    "kind": "video",
    "title": "History Video BSA",
    "brand": "BSA",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/STATICS/Copy%20of%20History%20Video%20BSA_V2.mp4",
    "w": 1080,
    "h": 1920,
    "tags": [
      "video"
    ]
  },
  {
    "id": "1-3",
    "kind": "static",
    "title": "80 Years of Happy Memories",
    "brand": "Havmor",
    "src": "/assets/ai/1-3.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "motul-news-ai-1",
    "kind": "video",
    "title": "Motul News AI 01",
    "brand": "Motul",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/STATICS/Copy%20of%20Motul%20news%20AI%20Final_1.mp4",
    "w": 1080,
    "h": 1920,
    "tags": [
      "video"
    ]
  },
  {
    "id": "bg-homework",
    "kind": "static",
    "title": "BG Homework",
    "brand": "",
    "src": "/assets/ai/bg-homework.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "mumbai-fc",
    "kind": "video",
    "title": "Mumbai City FC",
    "brand": "Mumbai City FC",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/STATICS/Copy%20of%20Mumbai%20fc.mp4",
    "w": 1080,
    "h": 1920,
    "tags": [
      "video"
    ]
  },
  {
    "id": "bg-long-weekend",
    "kind": "static",
    "title": "BG Long Weekend",
    "brand": "",
    "src": "/assets/ai/bg-long-weekend.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "t-rex",
    "kind": "video",
    "title": "T-Rex",
    "brand": "",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/STATICS/Copy%20of%20T-rex.mp4",
    "w": 1080,
    "h": 1920,
    "tags": [
      "video"
    ]
  },
  {
    "id": "bg-trip",
    "kind": "static",
    "title": "BG Trip",
    "brand": "",
    "src": "/assets/ai/bg-trip.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "ts-aiworld-jan2025",
    "kind": "video",
    "title": "TS AI World Jan2025",
    "brand": "",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/STATICS/Copy%20of%20TS_AIWorld_Jan2025.mp4",
    "w": 1080,
    "h": 1350,
    "tags": [
      "video"
    ]
  },
  {
    "id": "baisakhi-3",
    "kind": "static",
    "title": "Baisakhi 03",
    "brand": "",
    "src": "/assets/ai/baisakhi-3.webp",
    "w": 1080,
    "h": 1350,
    "tags": [
      "static"
    ]
  },
  {
    "id": "yippee-met-gala",
    "kind": "video",
    "title": "YIPPEE Met Gala",
    "brand": "Yippee",
    "src": "/assets/SC%20Website%20Revamp/05.%20AI%20work/STATICS/Copy%20of%20YIPPEE_Met%20Gala_9x16_HD.mp4",
    "w": 1080,
    "h": 1920,
    "tags": [
      "video"
    ]
  },
  {
    "id": "bali",
    "kind": "static",
    "title": "Bali",
    "brand": "",
    "src": "/assets/ai/bali.webp",
    "w": 1024,
    "h": 1024,
    "tags": [
      "static"
    ]
  },
  {
    "id": "brownie-dispenser",
    "kind": "static",
    "title": "Brownie Dispenser",
    "brand": "",
    "src": "/assets/ai/brownie-dispenser.webp",
    "w": 2048,
    "h": 2048,
    "tags": [
      "static"
    ]
  },
  {
    "id": "chalo-south-puthandu-power-post",
    "kind": "static",
    "title": "Chalo South Puthandu Power",
    "brand": "",
    "src": "/assets/ai/chalo-south-puthandu-power-post.webp",
    "w": 2000,
    "h": 2500,
    "tags": [
      "static"
    ]
  },
  {
    "id": "coke-barel",
    "kind": "static",
    "title": "Coke Barrel",
    "brand": "Coca-Cola",
    "src": "/assets/ai/coke-barel.webp",
    "w": 2048,
    "h": 2048,
    "tags": [
      "static"
    ]
  },
  {
    "id": "eid-post-5",
    "kind": "static",
    "title": "Eid 05",
    "brand": "",
    "src": "/assets/ai/eid-post-5.webp",
    "w": 2000,
    "h": 2500,
    "tags": [
      "static"
    ]
  },
  {
    "id": "gudhi-padwa",
    "kind": "static",
    "title": "Gudhi Padwa",
    "brand": "",
    "src": "/assets/ai/gudhi-padwa.webp",
    "w": 1080,
    "h": 1350,
    "tags": [
      "static"
    ]
  },
  {
    "id": "instant-energy",
    "kind": "static",
    "title": "Instant Energy",
    "brand": "",
    "src": "/assets/ai/instant-energy.webp",
    "w": 2000,
    "h": 2500,
    "tags": [
      "static"
    ]
  },
  {
    "id": "june-deck",
    "kind": "static",
    "title": "June Deck",
    "brand": "",
    "src": "/assets/ai/june-deck.webp",
    "w": 2000,
    "h": 2500,
    "tags": [
      "static"
    ]
  },
  {
    "id": "keyboard-linkedin-post-2",
    "kind": "static",
    "title": "Keyboard LinkedIn 02",
    "brand": "",
    "src": "/assets/ai/keyboard-linkedin-post-2.webp",
    "w": 2000,
    "h": 2000,
    "tags": [
      "static"
    ]
  },
  {
    "id": "labour-day-post-6",
    "kind": "static",
    "title": "Labour Day 06",
    "brand": "",
    "src": "/assets/ai/labour-day-post-6.webp",
    "w": 2000,
    "h": 2500,
    "tags": [
      "static"
    ]
  },
  {
    "id": "mhb-easter-2",
    "kind": "static",
    "title": "MHB Easter 02",
    "brand": "MHB",
    "src": "/assets/ai/mhb-easter-2.webp",
    "w": 1080,
    "h": 1350,
    "tags": [
      "static"
    ]
  },
  {
    "id": "mhb-lion-s-paw",
    "kind": "static",
    "title": "MHB Lion's Paw",
    "brand": "MHB",
    "src": "/assets/ai/mhb-lion-s-paw.webp",
    "w": 1080,
    "h": 1350,
    "tags": [
      "static"
    ]
  },
  {
    "id": "mango-barfi-larger-than-life-3",
    "kind": "static",
    "title": "Mango Barfi Larger Than Life 03",
    "brand": "",
    "src": "/assets/ai/mango-barfi-larger-than-life-3.webp",
    "w": 1080,
    "h": 1350,
    "tags": [
      "static"
    ]
  },
  {
    "id": "mothers-day-post-2",
    "kind": "static",
    "title": "Mother's Day 02",
    "brand": "",
    "src": "/assets/ai/mothers-day-post-2.webp",
    "w": 2000,
    "h": 2500,
    "tags": [
      "static"
    ]
  },
  {
    "id": "mothers-day-post-4",
    "kind": "static",
    "title": "Mother's Day 04",
    "brand": "",
    "src": "/assets/ai/mothers-day-post-4.webp",
    "w": 2000,
    "h": 2500,
    "tags": [
      "static"
    ]
  },
  {
    "id": "mothers-day-post-5",
    "kind": "static",
    "title": "Mother's Day 05",
    "brand": "",
    "src": "/assets/ai/mothers-day-post-5.webp",
    "w": 2000,
    "h": 2500,
    "tags": [
      "static"
    ]
  },
  {
    "id": "powerhouse-4",
    "kind": "static",
    "title": "Powerhouse 04",
    "brand": "",
    "src": "/assets/ai/powerhouse-4.webp",
    "w": 2000,
    "h": 2500,
    "tags": [
      "static"
    ]
  },
  {
    "id": "sibblings-day-3",
    "kind": "static",
    "title": "Siblings Day 03",
    "brand": "",
    "src": "/assets/ai/sibblings-day-3.webp",
    "w": 1080,
    "h": 1350,
    "tags": [
      "static"
    ]
  },
  {
    "id": "sibblings-day",
    "kind": "static",
    "title": "Siblings Day",
    "brand": "",
    "src": "/assets/ai/sibblings-day.webp",
    "w": 1080,
    "h": 1350,
    "tags": [
      "static"
    ]
  },
  {
    "id": "sibblings-day-2",
    "kind": "static",
    "title": "Siblings Day 02",
    "brand": "",
    "src": "/assets/ai/sibblings-day-2.webp",
    "w": 1080,
    "h": 1350,
    "tags": [
      "static"
    ]
  },
  {
    "id": "sleeping-pod-2",
    "kind": "static",
    "title": "Sleeping Pod 02",
    "brand": "",
    "src": "/assets/ai/sleeping-pod-2.webp",
    "w": 2048,
    "h": 2048,
    "tags": [
      "static"
    ]
  },
  {
    "id": "ai-pashute-2",
    "kind": "static",
    "title": "AI Pashute 02",
    "brand": "",
    "src": "/assets/ai/ai-pashute-2.webp",
    "w": 1080,
    "h": 1350,
    "tags": [
      "static"
    ]
  },
  {
    "id": "toilex-carousel-post-2",
    "kind": "static",
    "title": "Toilex Carousel 02",
    "brand": "Toilex",
    "src": "/assets/ai/toilex-carousel-post-2.webp",
    "w": 2000,
    "h": 2500,
    "tags": [
      "static"
    ]
  },
  {
    "id": "toilex-carousel-post-4",
    "kind": "static",
    "title": "Toilex Carousel 04",
    "brand": "Toilex",
    "src": "/assets/ai/toilex-carousel-post-4.webp",
    "w": 2000,
    "h": 2500,
    "tags": [
      "static"
    ]
  },
  {
    "id": "turbo-spin-mop-amazon-banner-2",
    "kind": "static",
    "title": "Turbo Spin Mop Amazon Banner 02",
    "brand": "",
    "src": "/assets/ai/turbo-spin-mop-amazon-banner-2.webp",
    "w": 2000,
    "h": 889,
    "tags": [
      "static"
    ]
  },
  {
    "id": "whatsapp-image-2025-05-06-at-1-06-20-pm",
    "kind": "static",
    "title": "Met Gala, in bulbs",
    "brand": "",
    "src": "/assets/ai/whatsapp-image-2025-05-06-at-1-06-20-pm.webp",
    "w": 1024,
    "h": 1536,
    "tags": [
      "static"
    ]
  },
  {
    "id": "whatsapp-image-2025-05-06-at-12-47-38-pm",
    "kind": "static",
    "title": "Met Gala, in namkeen",
    "brand": "",
    "src": "/assets/ai/whatsapp-image-2025-05-06-at-12-47-38-pm.webp",
    "w": 1024,
    "h": 1536,
    "tags": [
      "static"
    ]
  },
  {
    "id": "pool",
    "kind": "static",
    "title": "Pool",
    "brand": "",
    "src": "/assets/ai/pool.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "rock-climbing",
    "kind": "static",
    "title": "Rock Climbing",
    "brand": "",
    "src": "/assets/ai/rock-climbing.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  }
];
