/* GENERATED by scripts/build-ai-work.mjs - do not edit by hand.
   Re-run it after anything lands in or leaves
   assets/SC Website Revamp/05. AI work.

   89 assets, from 100 files on disk - the rest were
   byte-identical duplicates of something already here. Stills are
   re-encoded webp in /assets/ai; films are cut for the web into
   /assets/ai/films with a poster beside each. See lib/ai-content.ts for
   the shape and what the grid does with the tags. */
import type { AiAsset } from "./ai-content";

export const AI_WORK: AiAsset[] = [
  {
    "id": "halloween",
    "kind": "static",
    "title": "Halloween",
    "brand": "",
    "src": "/assets/ai/halloween.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "1",
    "kind": "video",
    "title": "Untitled film",
    "brand": "",
    "src": "/assets/ai/films/1.mp4",
    "poster": "/assets/ai/1-poster.webp",
    "w": 1080,
    "h": 1920,
    "tags": [
      "video"
    ]
  },
  {
    "id": "ai",
    "kind": "cgi",
    "title": "Untitled film",
    "brand": "",
    "src": "/assets/ai/films/ai.mp4",
    "poster": "/assets/ai/ai-poster.webp",
    "w": 1080,
    "h": 1920,
    "tags": [
      "cgi"
    ]
  },
  {
    "id": "skiing",
    "kind": "static",
    "title": "Skiing",
    "brand": "",
    "src": "/assets/ai/skiing.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "352stone-3d-kv",
    "kind": "video",
    "title": "352stone 3D KV",
    "brand": "352 Stone",
    "src": "/assets/ai/films/352stone-3d-kv.mp4",
    "poster": "/assets/ai/352stone-3d-kv-poster.webp",
    "w": 1920,
    "h": 1080,
    "tags": [
      "video"
    ]
  },
  {
    "id": "ai-waffle-video-01",
    "kind": "cgi",
    "title": "AI Waffle Video 01",
    "brand": "",
    "src": "/assets/ai/films/ai-waffle-video-01.mp4",
    "poster": "/assets/ai/ai-waffle-video-01-poster.webp",
    "w": 1080,
    "h": 1920,
    "tags": [
      "cgi"
    ]
  },
  {
    "id": "ai-grid-01",
    "kind": "static",
    "title": "AI Grid 01",
    "brand": "",
    "src": "/assets/ai/ai-grid-01.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "adding-comforting-scenes-in-your-life",
    "kind": "video",
    "title": "Adding Comforting Scenes In Your Life",
    "brand": "",
    "src": "/assets/ai/films/adding-comforting-scenes-in-your-life.mp4",
    "poster": "/assets/ai/adding-comforting-scenes-in-your-life-poster.webp",
    "w": 1080,
    "h": 1920,
    "tags": [
      "video"
    ]
  },
  {
    "id": "bajaj-cgi",
    "kind": "cgi",
    "title": "Bajaj CGI",
    "brand": "Bajaj",
    "src": "/assets/ai/films/bajaj-cgi.mp4",
    "poster": "/assets/ai/bajaj-cgi-poster.webp",
    "w": 2160,
    "h": 3840,
    "tags": [
      "cgi"
    ]
  },
  {
    "id": "ai-grid-02",
    "kind": "static",
    "title": "AI Grid 02",
    "brand": "",
    "src": "/assets/ai/ai-grid-02.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "admired",
    "kind": "video",
    "title": "Admired",
    "brand": "",
    "src": "/assets/ai/films/admired.mp4",
    "poster": "/assets/ai/admired-poster.webp",
    "w": 1920,
    "h": 1080,
    "tags": [
      "video"
    ]
  },
  {
    "id": "coconut-water-gif2",
    "kind": "cgi",
    "title": "Coconut Water GIF2",
    "brand": "",
    "src": "/assets/ai/films/coconut-water-gif2.mp4",
    "poster": "/assets/ai/coconut-water-gif2-poster.webp",
    "w": 1080,
    "h": 1920,
    "tags": [
      "cgi"
    ]
  },
  {
    "id": "ai-grid-03",
    "kind": "static",
    "title": "AI Grid 03",
    "brand": "",
    "src": "/assets/ai/ai-grid-03.webp",
    "w": 1079,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "announcement-video-back-sticker",
    "kind": "video",
    "title": "Announcement Video Back Sticker",
    "brand": "",
    "src": "/assets/ai/films/announcement-video-back-sticker.mp4",
    "poster": "/assets/ai/announcement-video-back-sticker-poster.webp",
    "w": 1080,
    "h": 1920,
    "tags": [
      "video"
    ]
  },
  {
    "id": "aghori-title-animation",
    "kind": "cgi",
    "title": "Aghori Title Animation",
    "brand": "Aghori",
    "src": "/assets/ai/films/aghori-title-animation.mp4",
    "poster": "/assets/ai/aghori-title-animation-poster.webp",
    "w": 1920,
    "h": 1080,
    "tags": [
      "cgi"
    ]
  },
  {
    "id": "moon",
    "kind": "static",
    "title": "Moon",
    "brand": "",
    "src": "/assets/ai/moon.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "ashutosh-character-promo-yt-03",
    "kind": "video",
    "title": "Ashutosh Character Promo YT 03",
    "brand": "",
    "src": "/assets/ai/films/ashutosh-character-promo-yt-03.mp4",
    "poster": "/assets/ai/ashutosh-character-promo-yt-03-poster.webp",
    "w": 1080,
    "h": 1920,
    "tags": [
      "video"
    ]
  },
  {
    "id": "em5-aghori",
    "kind": "cgi",
    "title": "EM5 Aghori",
    "brand": "Aghori",
    "src": "/assets/ai/films/em5-aghori.mp4",
    "poster": "/assets/ai/em5-aghori-poster.webp",
    "w": 1080,
    "h": 1920,
    "tags": [
      "cgi"
    ]
  },
  {
    "id": "5",
    "kind": "static",
    "title": "Welcome the Royal",
    "brand": "Monarch",
    "src": "/assets/ai/5.webp",
    "w": 1350,
    "h": 2400,
    "tags": [
      "static"
    ]
  },
  {
    "id": "jhs-akotsk-ep-3-egg-cut",
    "kind": "video",
    "title": "JHS AKOTSK EP 3 Egg Cut",
    "brand": "JHS",
    "src": "/assets/ai/films/jhs-akotsk-ep-3-egg-cut.mp4",
    "poster": "/assets/ai/jhs-akotsk-ep-3-egg-cut-poster.webp",
    "w": 1080,
    "h": 1920,
    "tags": [
      "video"
    ]
  },
  {
    "id": "samurai-attack-reel-6",
    "kind": "cgi",
    "title": "SAMURAI ATTACK REEL 06",
    "brand": "Samurai",
    "src": "/assets/ai/films/samurai-attack-reel-6.mp4",
    "poster": "/assets/ai/samurai-attack-reel-6-poster.webp",
    "w": 1920,
    "h": 1080,
    "tags": [
      "cgi"
    ]
  },
  {
    "id": "ai-gaming",
    "kind": "static",
    "title": "AI Gaming",
    "brand": "",
    "src": "/assets/ai/ai-gaming.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "kiss-the-waffle",
    "kind": "video",
    "title": "Kiss The Waffle",
    "brand": "",
    "src": "/assets/ai/films/kiss-the-waffle.mp4",
    "poster": "/assets/ai/kiss-the-waffle-poster.webp",
    "w": 1080,
    "h": 1920,
    "tags": [
      "video"
    ]
  },
  {
    "id": "spiderpunk-coming-soon",
    "kind": "cgi",
    "title": "Spider-Punk Coming Soon",
    "brand": "Spider-Punk",
    "src": "/assets/ai/films/spiderpunk-coming-soon.mp4",
    "poster": "/assets/ai/spiderpunk-coming-soon-poster.webp",
    "w": 1080,
    "h": 1920,
    "tags": [
      "cgi"
    ]
  },
  {
    "id": "independence-day",
    "kind": "static",
    "title": "Independence Day",
    "brand": "",
    "src": "/assets/ai/independence-day.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "london-dry-bts-complex",
    "kind": "video",
    "title": "London Dry BTS Complex",
    "brand": "London Dry",
    "src": "/assets/ai/films/london-dry-bts-complex.mp4",
    "poster": "/assets/ai/london-dry-bts-complex-poster.webp",
    "w": 1080,
    "h": 1920,
    "tags": [
      "video"
    ]
  },
  {
    "id": "yippee-bau-halloween",
    "kind": "cgi",
    "title": "YIPPEE BAU Halloween",
    "brand": "Yippee",
    "src": "/assets/ai/films/yippee-bau-halloween.mp4",
    "poster": "/assets/ai/yippee-bau-halloween-poster.webp",
    "w": 1080,
    "h": 1920,
    "tags": [
      "cgi"
    ]
  },
  {
    "id": "ai-frisbee",
    "kind": "static",
    "title": "AI Frisbee",
    "brand": "",
    "src": "/assets/ai/ai-frisbee.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "reelvideo-57616",
    "kind": "video",
    "title": "Reel",
    "brand": "",
    "src": "/assets/ai/films/reelvideo-57616.mp4",
    "poster": "/assets/ai/reelvideo-57616-poster.webp",
    "w": 720,
    "h": 1280,
    "tags": [
      "video"
    ]
  },
  {
    "id": "yippee-bau-navratri",
    "kind": "cgi",
    "title": "YIPPEE BAU Navratri",
    "brand": "Yippee",
    "src": "/assets/ai/films/yippee-bau-navratri.mp4",
    "poster": "/assets/ai/yippee-bau-navratri-poster.webp",
    "w": 1080,
    "h": 1920,
    "tags": [
      "cgi"
    ]
  },
  {
    "id": "nacho-ship",
    "kind": "static",
    "title": "Nacho Ship",
    "brand": "",
    "src": "/assets/ai/nacho-ship.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "meet-your-product-02",
    "kind": "video",
    "title": "Meet Your Product 02",
    "brand": "",
    "src": "/assets/ai/films/meet-your-product-02.mp4",
    "poster": "/assets/ai/meet-your-product-02-poster.webp",
    "w": 1080,
    "h": 1350,
    "tags": [
      "video"
    ]
  },
  {
    "id": "havmor-heartbeat-reel",
    "kind": "cgi",
    "title": "Havmor Heartbeat Reel",
    "brand": "Havmor",
    "src": "/assets/ai/films/havmor-heartbeat-reel.mp4",
    "poster": "/assets/ai/havmor-heartbeat-reel-poster.webp",
    "w": 1080,
    "h": 1920,
    "tags": [
      "cgi"
    ]
  },
  {
    "id": "a-to-z-linkedin-post-5",
    "kind": "static",
    "title": "A To Z LinkedIn 05",
    "brand": "",
    "src": "/assets/ai/a-to-z-linkedin-post-5.webp",
    "w": 2000,
    "h": 2500,
    "tags": [
      "static"
    ]
  },
  {
    "id": "ai-waffle-video-02",
    "kind": "video",
    "title": "AI Waffle Video 02",
    "brand": "",
    "src": "/assets/ai/films/ai-waffle-video-02.mp4",
    "poster": "/assets/ai/ai-waffle-video-02-poster.webp",
    "w": 1080,
    "h": 1920,
    "tags": [
      "video"
    ]
  },
  {
    "id": "havmor-kj-reel",
    "kind": "cgi",
    "title": "Havmor KJ Reel",
    "brand": "Havmor",
    "src": "/assets/ai/films/havmor-kj-reel.mp4",
    "poster": "/assets/ai/havmor-kj-reel-poster.webp",
    "w": 1080,
    "h": 1920,
    "tags": [
      "cgi"
    ]
  },
  {
    "id": "ai-2",
    "kind": "static",
    "title": "Waffle on the Moon",
    "brand": "The Belgian Waffle Co.",
    "src": "/assets/ai/ai-2.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "ai-backgrounds",
    "kind": "video",
    "title": "AI Backgrounds",
    "brand": "",
    "src": "/assets/ai/films/ai-backgrounds.mp4",
    "poster": "/assets/ai/ai-backgrounds-poster.webp",
    "w": 1080,
    "h": 1920,
    "tags": [
      "video"
    ]
  },
  {
    "id": "ai-reel",
    "kind": "cgi",
    "title": "AI Reel",
    "brand": "",
    "src": "/assets/ai/films/ai-reel.mp4",
    "poster": "/assets/ai/ai-reel-poster.webp",
    "w": 1080,
    "h": 1920,
    "tags": [
      "cgi"
    ]
  },
  {
    "id": "ai-carousel-6",
    "kind": "static",
    "title": "AI Carousel 06",
    "brand": "",
    "src": "/assets/ai/ai-carousel-6.webp",
    "w": 2000,
    "h": 2500,
    "tags": [
      "static"
    ]
  },
  {
    "id": "angry-sun",
    "kind": "video",
    "title": "Angry Sun",
    "brand": "",
    "src": "/assets/ai/films/angry-sun.mp4",
    "poster": "/assets/ai/angry-sun-poster.webp",
    "w": 1080,
    "h": 1350,
    "tags": [
      "video"
    ]
  },
  {
    "id": "galentine-reel-f",
    "kind": "cgi",
    "title": "Galentine Reel F",
    "brand": "",
    "src": "/assets/ai/films/galentine-reel-f.mp4",
    "poster": "/assets/ai/galentine-reel-f-poster.webp",
    "w": 1080,
    "h": 1920,
    "tags": [
      "cgi"
    ]
  },
  {
    "id": "ai-jpg2",
    "kind": "static",
    "title": "Moonrise Waffle",
    "brand": "The Belgian Waffle Co.",
    "src": "/assets/ai/ai-jpg2.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "battery-low",
    "kind": "video",
    "title": "Battery Low",
    "brand": "",
    "src": "/assets/ai/films/battery-low.mp4",
    "poster": "/assets/ai/battery-low-poster.webp",
    "w": 1080,
    "h": 1920,
    "tags": [
      "video"
    ]
  },
  {
    "id": "ai-1",
    "kind": "static",
    "title": "Noodles in the Wild",
    "brand": "Yippee",
    "src": "/assets/ai/ai-1.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "bingo-x-swiggy-mad-angles",
    "kind": "video",
    "title": "Bingo X Swiggy Mad Angles",
    "brand": "Swiggy",
    "src": "/assets/ai/films/bingo-x-swiggy-mad-angles.mp4",
    "poster": "/assets/ai/bingo-x-swiggy-mad-angles-poster.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "video"
    ]
  },
  {
    "id": "ai-2-2",
    "kind": "static",
    "title": "Noodle Valley",
    "brand": "Yippee",
    "src": "/assets/ai/ai-2-2.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "got-1",
    "kind": "video",
    "title": "GOT 01",
    "brand": "",
    "src": "/assets/ai/films/got-1.mp4",
    "poster": "/assets/ai/got-1-poster.webp",
    "w": 1080,
    "h": 1920,
    "tags": [
      "video"
    ]
  },
  {
    "id": "arcade",
    "kind": "static",
    "title": "Arcade",
    "brand": "",
    "src": "/assets/ai/arcade.webp",
    "w": 2048,
    "h": 2048,
    "tags": [
      "static"
    ]
  },
  {
    "id": "history-video-bsa",
    "kind": "video",
    "title": "History Video BSA",
    "brand": "BSA",
    "src": "/assets/ai/films/history-video-bsa.mp4",
    "poster": "/assets/ai/history-video-bsa-poster.webp",
    "w": 1080,
    "h": 1920,
    "tags": [
      "video"
    ]
  },
  {
    "id": "1-3",
    "kind": "static",
    "title": "80 Years of Happy Memories",
    "brand": "Havmor",
    "src": "/assets/ai/1-3.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "motul-news-ai-1",
    "kind": "video",
    "title": "Motul News AI 01",
    "brand": "Motul",
    "src": "/assets/ai/films/motul-news-ai-1.mp4",
    "poster": "/assets/ai/motul-news-ai-1-poster.webp",
    "w": 1080,
    "h": 1920,
    "tags": [
      "video"
    ]
  },
  {
    "id": "bg-homework",
    "kind": "static",
    "title": "BG Homework",
    "brand": "",
    "src": "/assets/ai/bg-homework.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "mumbai-fc",
    "kind": "video",
    "title": "Mumbai City FC",
    "brand": "Mumbai City FC",
    "src": "/assets/ai/films/mumbai-fc.mp4",
    "poster": "/assets/ai/mumbai-fc-poster.webp",
    "w": 1080,
    "h": 1920,
    "tags": [
      "video"
    ]
  },
  {
    "id": "bg-long-weekend",
    "kind": "static",
    "title": "BG Long Weekend",
    "brand": "",
    "src": "/assets/ai/bg-long-weekend.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "t-rex",
    "kind": "video",
    "title": "T-Rex",
    "brand": "",
    "src": "/assets/ai/films/t-rex.mp4",
    "poster": "/assets/ai/t-rex-poster.webp",
    "w": 1080,
    "h": 1920,
    "tags": [
      "video"
    ]
  },
  {
    "id": "bg-trip",
    "kind": "static",
    "title": "BG Trip",
    "brand": "",
    "src": "/assets/ai/bg-trip.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "ts-aiworld-jan2025",
    "kind": "video",
    "title": "TS AI World Jan2025",
    "brand": "",
    "src": "/assets/ai/films/ts-aiworld-jan2025.mp4",
    "poster": "/assets/ai/ts-aiworld-jan2025-poster.webp",
    "w": 1080,
    "h": 1350,
    "tags": [
      "video"
    ]
  },
  {
    "id": "baisakhi-3",
    "kind": "static",
    "title": "Baisakhi 03",
    "brand": "",
    "src": "/assets/ai/baisakhi-3.webp",
    "w": 1080,
    "h": 1350,
    "tags": [
      "static"
    ]
  },
  {
    "id": "yippee-met-gala",
    "kind": "video",
    "title": "YIPPEE Met Gala",
    "brand": "Yippee",
    "src": "/assets/ai/films/yippee-met-gala.mp4",
    "poster": "/assets/ai/yippee-met-gala-poster.webp",
    "w": 1080,
    "h": 1920,
    "tags": [
      "video"
    ]
  },
  {
    "id": "bali",
    "kind": "static",
    "title": "Bali",
    "brand": "",
    "src": "/assets/ai/bali.webp",
    "w": 1024,
    "h": 1024,
    "tags": [
      "static"
    ]
  },
  {
    "id": "brownie-dispenser",
    "kind": "static",
    "title": "Brownie Dispenser",
    "brand": "",
    "src": "/assets/ai/brownie-dispenser.webp",
    "w": 2048,
    "h": 2048,
    "tags": [
      "static"
    ]
  },
  {
    "id": "chalo-south-puthandu-power-post",
    "kind": "static",
    "title": "Chalo South Puthandu Power",
    "brand": "",
    "src": "/assets/ai/chalo-south-puthandu-power-post.webp",
    "w": 2000,
    "h": 2500,
    "tags": [
      "static"
    ]
  },
  {
    "id": "coke-barel",
    "kind": "static",
    "title": "Coke Barrel",
    "brand": "Coca-Cola",
    "src": "/assets/ai/coke-barel.webp",
    "w": 2048,
    "h": 2048,
    "tags": [
      "static"
    ]
  },
  {
    "id": "eid-post-5",
    "kind": "static",
    "title": "Eid 05",
    "brand": "",
    "src": "/assets/ai/eid-post-5.webp",
    "w": 2000,
    "h": 2500,
    "tags": [
      "static"
    ]
  },
  {
    "id": "gudhi-padwa",
    "kind": "static",
    "title": "Gudhi Padwa",
    "brand": "",
    "src": "/assets/ai/gudhi-padwa.webp",
    "w": 1080,
    "h": 1350,
    "tags": [
      "static"
    ]
  },
  {
    "id": "instant-energy",
    "kind": "static",
    "title": "Instant Energy",
    "brand": "",
    "src": "/assets/ai/instant-energy.webp",
    "w": 2000,
    "h": 2500,
    "tags": [
      "static"
    ]
  },
  {
    "id": "june-deck",
    "kind": "static",
    "title": "June Deck",
    "brand": "",
    "src": "/assets/ai/june-deck.webp",
    "w": 2000,
    "h": 2500,
    "tags": [
      "static"
    ]
  },
  {
    "id": "keyboard-linkedin-post-2",
    "kind": "static",
    "title": "Keyboard LinkedIn 02",
    "brand": "",
    "src": "/assets/ai/keyboard-linkedin-post-2.webp",
    "w": 2000,
    "h": 2000,
    "tags": [
      "static"
    ]
  },
  {
    "id": "labour-day-post-6",
    "kind": "static",
    "title": "Labour Day 06",
    "brand": "",
    "src": "/assets/ai/labour-day-post-6.webp",
    "w": 2000,
    "h": 2500,
    "tags": [
      "static"
    ]
  },
  {
    "id": "mhb-easter-2",
    "kind": "static",
    "title": "MHB Easter 02",
    "brand": "MHB",
    "src": "/assets/ai/mhb-easter-2.webp",
    "w": 1080,
    "h": 1350,
    "tags": [
      "static"
    ]
  },
  {
    "id": "mhb-lion-s-paw",
    "kind": "static",
    "title": "MHB Lion's Paw",
    "brand": "MHB",
    "src": "/assets/ai/mhb-lion-s-paw.webp",
    "w": 1080,
    "h": 1350,
    "tags": [
      "static"
    ]
  },
  {
    "id": "mango-barfi-larger-than-life-3",
    "kind": "static",
    "title": "Mango Barfi Larger Than Life 03",
    "brand": "",
    "src": "/assets/ai/mango-barfi-larger-than-life-3.webp",
    "w": 1080,
    "h": 1350,
    "tags": [
      "static"
    ]
  },
  {
    "id": "mothers-day-post-2",
    "kind": "static",
    "title": "Mother's Day 02",
    "brand": "",
    "src": "/assets/ai/mothers-day-post-2.webp",
    "w": 2000,
    "h": 2500,
    "tags": [
      "static"
    ]
  },
  {
    "id": "mothers-day-post-4",
    "kind": "static",
    "title": "Mother's Day 04",
    "brand": "",
    "src": "/assets/ai/mothers-day-post-4.webp",
    "w": 2000,
    "h": 2500,
    "tags": [
      "static"
    ]
  },
  {
    "id": "mothers-day-post-5",
    "kind": "static",
    "title": "Mother's Day 05",
    "brand": "",
    "src": "/assets/ai/mothers-day-post-5.webp",
    "w": 2000,
    "h": 2500,
    "tags": [
      "static"
    ]
  },
  {
    "id": "powerhouse-4",
    "kind": "static",
    "title": "Powerhouse 04",
    "brand": "",
    "src": "/assets/ai/powerhouse-4.webp",
    "w": 2000,
    "h": 2500,
    "tags": [
      "static"
    ]
  },
  {
    "id": "sibblings-day-3",
    "kind": "static",
    "title": "Siblings Day 03",
    "brand": "",
    "src": "/assets/ai/sibblings-day-3.webp",
    "w": 1080,
    "h": 1350,
    "tags": [
      "static"
    ]
  },
  {
    "id": "sibblings-day",
    "kind": "static",
    "title": "Siblings Day",
    "brand": "",
    "src": "/assets/ai/sibblings-day.webp",
    "w": 1080,
    "h": 1350,
    "tags": [
      "static"
    ]
  },
  {
    "id": "sibblings-day-2",
    "kind": "static",
    "title": "Siblings Day 02",
    "brand": "",
    "src": "/assets/ai/sibblings-day-2.webp",
    "w": 1080,
    "h": 1350,
    "tags": [
      "static"
    ]
  },
  {
    "id": "sleeping-pod-2",
    "kind": "static",
    "title": "Sleeping Pod 02",
    "brand": "",
    "src": "/assets/ai/sleeping-pod-2.webp",
    "w": 2048,
    "h": 2048,
    "tags": [
      "static"
    ]
  },
  {
    "id": "ai-pashute-2",
    "kind": "static",
    "title": "AI Pashute 02",
    "brand": "",
    "src": "/assets/ai/ai-pashute-2.webp",
    "w": 1080,
    "h": 1350,
    "tags": [
      "static"
    ]
  },
  {
    "id": "toilex-carousel-post-2",
    "kind": "static",
    "title": "Toilex Carousel 02",
    "brand": "Toilex",
    "src": "/assets/ai/toilex-carousel-post-2.webp",
    "w": 2000,
    "h": 2500,
    "tags": [
      "static"
    ]
  },
  {
    "id": "toilex-carousel-post-4",
    "kind": "static",
    "title": "Toilex Carousel 04",
    "brand": "Toilex",
    "src": "/assets/ai/toilex-carousel-post-4.webp",
    "w": 2000,
    "h": 2500,
    "tags": [
      "static"
    ]
  },
  {
    "id": "turbo-spin-mop-amazon-banner-2",
    "kind": "static",
    "title": "Turbo Spin Mop Amazon Banner 02",
    "brand": "",
    "src": "/assets/ai/turbo-spin-mop-amazon-banner-2.webp",
    "w": 2000,
    "h": 889,
    "tags": [
      "static"
    ]
  },
  {
    "id": "whatsapp-image-2025-05-06-at-1-06-20-pm",
    "kind": "static",
    "title": "Met Gala, in bulbs",
    "brand": "",
    "src": "/assets/ai/whatsapp-image-2025-05-06-at-1-06-20-pm.webp",
    "w": 1024,
    "h": 1536,
    "tags": [
      "static"
    ]
  },
  {
    "id": "whatsapp-image-2025-05-06-at-12-47-38-pm",
    "kind": "static",
    "title": "Met Gala, in namkeen",
    "brand": "",
    "src": "/assets/ai/whatsapp-image-2025-05-06-at-12-47-38-pm.webp",
    "w": 1024,
    "h": 1536,
    "tags": [
      "static"
    ]
  },
  {
    "id": "pool",
    "kind": "static",
    "title": "Pool",
    "brand": "",
    "src": "/assets/ai/pool.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  },
  {
    "id": "rock-climbing",
    "kind": "static",
    "title": "Rock Climbing",
    "brand": "",
    "src": "/assets/ai/rock-climbing.webp",
    "w": 1080,
    "h": 1080,
    "tags": [
      "static"
    ]
  }
];
